- type: job
  id: GliessianSheriff
  name: job-name-gliess-sheriff
  description: job-description-gliess-sheriff
  playTimeTracker: JobGliessSheriff
  weight: 40
  startingGear: GliessSheriffGear
  icon: "JobIconMarshal"
  supervisors: job-supervisors-gliess
  requirements:
    - !type:CharacterWhitelistRequirement
#    - !type:CharacterOverallTimeRequirement
#      min: 25000
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ind-gliess-sheriff
      - type: HullrotFaction
        faction: GS
      - type: LanguageAdder
        addSpoken:
          - Tradeband
        addUnderstood:
          - Tradeband
  accessGroups:
  - GeneralAccess
  access:
  - GliessSheriff
  - GliessDockmaster

- type: startingGear
  id: GliessSheriffGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMOfficer
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatCMMMarshal
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMinutemanPouches
    pocket1: WeaponRevolverSnubnose
    id: GliessSheriffPDA
    ears: ClothingHeadsetCMM
    outerClothing: ClothingOuterArmorCMMCarapace
