- type: job
  id: ArchmaesterDSM
  name: job-name-archmaester
  description: job-description-archmaester
  playTimeTracker: JobArchmaesterDSM
  weight: 94
  startingGear: ArchmaesterGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconArchmaester"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:FactionRequirement
      factionID: "DSM"
#    - !type:CharacterOverallTimeRequirement
#      min: 36000
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-archmaester
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - HighImperial
          - LowImperial
          - Tradeband
        addUnderstood:
          - HighImperial
          - LowImperial
          - Tradeband
  access:
  - Command
  - Empire
  - Maintenance
  - ScribesGuild
  - Archmaester
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ArchmaesterGear
  equipment:
    id: ArchmaesterPDA
    ears: ClothingHeadsetEmpire
    pocket1: ImperialPassportBareLegit
    back: ClothingBackpackSatchelLeatherFilledDSM
    outerClothing: ClothingOuterCoatArchmaester
    mask: ClothingMaskImperialAdjutantMask
    shoes: ClothingShoesBootsImperialLaceup
    jumpsuit: ClothingUniformJumpsuitImperialArchmaester
